//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaOtoSis.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiletTuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BiletTuru()
        {
            this.BiletSatis = new HashSet<BiletSatis>();
        }
    
        public int BiletTurID { get; set; }
        public string BiletTuru1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiletSatis> BiletSatis { get; set; }
    }
}
